### ISSUE TITLE
demand less from the environment

### ISSUE THREAD

**Issue by c-cube** [janestreet/sexplib0#3]
Why does such a basic package that is supposed to be usable as widely as possible to facilitate interoperability within the community have such requirements?

- ocaml 4.04
- dune 1.5

edit: maybe there should be a global `base-sexp` package with just the type definition, so y'all don't have to change your workflow.

**Comment by aalekseyev** [comment]
Can you give an example of what configuration you'd like sexplib0 to be compatible with?
It seems that sexplib0 is already unusual among Jane Street libraries in that it's compatible with 4.04 rather than just >=4.08.

As for package with just a type, that doesn't sound too bad, but I'd still like to understand the use case.

**Comment by c-cube** [comment]
well, I don't really care anymore since I functorized my own code. But if you want a compatibility package, such as bytes or seq on opam, you really want to have as few constraints as possible on them. When I filed this I think 4.03 was still the debian stable version.
